version: 1
validation: sovereign
genesis:
  app_state:
    staking:
      params:
        bond_denom: "push" # Removed "token", replaced "stake" with "push"
build:
  binary: "pushchaind"
accounts: 
- name: a1
  coins:
  - 200000000push  # Removed "token", replaced "stake" with "push"
  mnemonic: control patient rural venue giant output method copy you envelope burger odor chaos ring hamster network elegant true rich brief goddess valid present intact
- name: a2
  coins:
  - 200000000push   # Removed "token", replaced "stake" with "push"
  mnemonic: mixture sleep uncle critic favorite truly timber unusual push twice copy voice bag iron abstract deer gym swallow save vast reflect mandate fantasy gorilla
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: a2
  coins:
  - 500000push      # Simplified to only "push"
validators:
- name: a1
  bonded: 100000000push  # Replaced "stake" with "push"
  app:
    minimum-gas-prices: "0.00025push"  # Gas price now uses "push"
- name: validator1
  bonded: 100000000push
- name: validator2
  bonded: 200000000push
- name: validator3
  bonded: 300000000push