version: 1

accounts:
  - address: push10v5gps9vvp70af7wvldtp784vt8ww0mkx6m4v0
    coins:
      - 5000000000000000000000000apush
  - name: alice
    coins:
      - 5000000000000000000000000apush
      - 5000000000000000000000000stake
    keys:
      keyring-backend: "test"
      consensus-pubkey-type: "ed25519"
  - name: bob
    coins:
      - 500000000000000000000apush
      - 500000000000000000000stake

client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
  - name: alice
    bonded: 1500000000000000000stake
    minimum-gas-prices: "1apush"
    client:
      keyring-backend: "test"
    app:
      minimum-gas-prices: "0apush"
      api:
        enable: true
      json-rpc:
        enable: true
        api: "eth,net,web3,personal"
        address: "0.0.0.0:8545"
        ws-address: "0.0.0.0:8546"
        gas-cap: "250000000"
        evm-timeout: "5s"
        txfee-cap: "1"
        filter-cap: "200"
        feehistory-cap: "100"
        logs-cap: "10000"
        block-range-cap: "10000"
        http-timeout: "30s"
        http-idle-timeout: "2m0s"
        allow-unprotected-txs: true
        max-open-connections: "0"
        enable-indexer: true
    config:
      proxy_app: "tcp://127.0.0.1:26658"
      fast_sync: false
      db_backend: "goleveldb"
      db_dir: "data"
      log_level: "info"
      consensus:
        create_empty_blocks: true
        create_empty_blocks_interval: "0s"
        timeout_commit: "1s"
      p2p:
        laddr: "tcp://0.0.0.0:26656"
        addr_book_strict: false  # Disable strict address book rules
        pex: false              # Disable peer exchange
        seed_mode: false
        allow_duplicate_ip: true
        external_address: ""
        seeds: ""
        persistent_peers: ""
        max_num_inbound_peers: "0"   # Disable peer connections
        max_num_outbound_peers: "0"  # Disable peer connections
      mempool:
        version: "v0"
        size: "5000"
        max_txs_bytes: "1073741824"
        cache_size: "10000"
        max_tx_bytes: "1048576"
      tx_index:
        indexer: "kv"
      instrumentation:
        prometheus: true
        prometheus_listen_addr: ":26660"
        max_open_connections: "3"
        namespace: "tendermint"
      rpc:
        laddr: "tcp://0.0.0.0:26657"
        cors_allowed_origins: []
        cors_allowed_methods: ["HEAD", "GET", "POST"]
        cors_allowed_headers: ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time"]
        grpc_max_open_connections: "900"
        max_open_connections: "900"
        max_subscription_clients: "100"
        max_subscriptions_per_client: "5"
        experimental_subscription_buffer_size: "200"
        timeout_broadcast_tx_commit: "10s"
        max_body_bytes: "1000000"
        max_header_bytes: "1048576"
        tls_cert_file: ""
        tls_key_file: ""

genesis:
  chain_id: "pushchain_9000-1"
  consensus_params:
    block:
      max_bytes: "22020096"
      max_gas: "30000000"  # Set default block gas limit
      time_iota_ms: "1000"
  app_state:
    evm:
      params:
        evm_denom: "apush"
        enable_create: true
        enable_call: true
        allow_unprotected_txs: true
        extra_eips: []
    feemarket:
      params:
        no_base_fee: true
        base_fee: "0"
        min_gas_price: "0"
        min_gas_multiplier: "0"
        enable_height: "0"
        base_fee_change_denominator: "8"
        elasticity_multiplier: "2"