version: 1
validation: sovereign
genesis:
  chain_id: "pcv-1" 
  app_state:
    staking:
      params:
        bond_denom: "tpc"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "tpc"
    crisis:
      constant_fee:
        amount: "1000"
        denom: "tpc"
    mint:
      params:
        mint_denom: "tpc"
app:
  minimum-gas-prices: "0.025tpc"  
accounts:
  - name: alice
    coins:
      - "2000000000000tpc"  
  - name: bob
    coins:
      - "10000tpc"          
  - name: validator1     
    coins:
      - "100000000tpc"
  - name: validator2     
    coins:
      - "200000000tpc"
  - name: validator3     
    coins:
      - "300000000tpc"
client:
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins:
    - "5tpc"            
validators:
  - name: alice
    bonded: "100000000tpc"
  - name: validator1
    bonded: "100000000tpc"
  - name: validator2
    bonded: "200000000tpc"
  - name: validator3
    bonded: "300000000tpc"
keyring-backend: test     