version: 1
validation: sovereign
genesis:
  app_state:
    staking:
      params:
        bond_denom: "push" # Removed "token", replaced "stake" with "push"
build:
  binary: "pushchaind"
accounts: 
- name: alice
  coins:
  - 200000000push  # Removed "token", replaced "stake" with "push"
- name: bob
  coins:
  - 100000000push   # Removed "token", replaced "stake" with "push"
- name: faucet
  coins:
  - 100000000000000push
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 500000push      # Simplified to only "push"
validators:
- name: alice
  bonded: 100000000push  # Replaced "stake" with "push"
  app:
    minimum-gas-prices: "0.00025push"  # Gas price now uses "push"
- name: validator1
  bonded: 100000000push
- name: validator2
  bonded: 200000000push
- name: validator3
  bonded: 300000000push